name: question-service-test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: question-service  
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install mocha
        run: npm install mocha
      - name: Install dependencies
        run: npm install
      - name: "Run Test"
        run: npm test