name: question-service-test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./question-service  
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: "npm"
          cache-dependency-path: "./question-service"
      - name: Install dependencies
        run: npm i -g npm@latest
      - name: "Run Test"
        run: npm test