name: user-service-test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./user-service  
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install mocha
        run: npm install -g mocha
      - name: Install dependencies
        run: npm install 
      - name: "Run Test"
        run: npm test