name: user-service-test
on: [push]

defaults:
  run:
    working-directory: user-service

jobs:
  test-user-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: "user-service/package-lock.json"
      - name: Download dependencies   
        run: |
          npm ci
          npm update
      - name: Download dependencies and run test cases    
        run: npm test
          