name: user-service-test
on: [push]

defaults:
  run:
    working-directory: user-service

jobs:
  test-user-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install dependencies
      run: npm ci
    - name: Update dependencies
      run: npm update
    - name: "Run Test"
      run: npm test